### File: leavitt_law_calibration.toml

[project]
name = "leavitt_law_calibration"
version = "0.0.1"
authors = [
  { name="Shubham Mamgain", email="mshubham00@gmail.com" },
]
description = "Require Cepheid dataset with distance, reddening and multiband photometry."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/mshubham00/leavitt_law_calibration"
Issues = "https://github.com/mshubham00/"

